---
geometry: a5paper, landscape, top=1.5cm, bottom=0.9cm, left=0.5cm, right=0.5cm, headsep = 0.5cm, footskip = 12pt
output:
  pdf_document: 
    latex_engine: xelatex
    template: A5_Zettel.tex
sansfont: "Gill Sans"
mainfont: "Bookman Old Style"
printpaper: yes
---