---
title: Función para obtener valores propios de una matriz en R
author: Author Name
header: R01M0702
footer: \#Estadística\slash R \#Programación\slash R \#R\slash Matrices
geometry: a5paper, landscape, top=1.5cm, bottom=0.9cm, left=0.5cm, right=0.5cm, headsep = 0.5cm, footskip = 12pt
output:
  pdf_document: 
    template: A5_Zettel.tex
sansfont: Calibri Light
seriffont: "Bookman Old Style"
printpaper: no
verbatim-in-note: yes
---
### `eigen(matriz)` 
- Calcula los valores **vaps** y vectores propios **veps**

Si hay algún vap con multiplicidad algebraica mayor que 1 (es decir, que aparece más de una vez), la función `eigen()` da tantos valores de este vap como su multiplicidad algebraica indica. Además, en este caso, R intenta que los veps asociados a cada uno de estos vaps sean **linealmente independientes** [**R01A02**]. Por tanto, cuando como resultado obtenemos veps repetidos asociados a un vap de multiplicidad algebraica mayor que 1, es porque para este vap no existen tantos veps linealmente independientes como su multiplicidad algebraica y, por consiguiente, la matriz no es **diagonalizable** **R01A03**.

### `eigen(matriz)$values`
- Nos da el vector con los vaps de la matriz en orden decreciente de su valor absoluto y repetidos tantas veces como su multiplicidad algebraica.

### `eigen(matriz)$vectors`
- Nos da una matriz cuyas columnas son los veps de la matriz.

## Ejemplo: [[**R01A01** |Descomposición canónica de matrices en R]]

## Ejemplo:
```{r}
M = matrix(c(0,1,0,-7,3,-1,16,-3,4), nrow = 3, byrow = TRUE)
eigen(M)$values
```

\pagebreak

# Referencias

**Gomilla, J. J.** (2022). _Curso completo des Estadística descriptiva - RStudio y Python. Vectores y tipos de datos en R_. Retrieved 2024, from <code style="word-wrap: break-word;">https://cursos.frogamesformacion.com/courses/take/estadistica-descriptiva/lessons/33618869-un-repaso-de-algebra-lineal</code>.