---
title: Vectores en R
author: Author Name
header: R01V01
footer: \#Estadística\slash R \#Programación\slash R \#R\slash Vectores
geometry: a5paper, landscape, top=1.5cm, bottom=0.9cm, left=0.5cm, right=0.5cm, headsep = 0.5cm, footskip = 12pt
output:
  pdf_document:
      template: warro.tex
sansfont: Calibri Light
seriffont: "Bookman Old Style"
fontsize: 8pt
bibliography: test.bib
nocite:
header-includes: |
    \AtBeginDocument{\let\maketitle\relax  \leading{6.5mm} \setlength\baselineskip{6.5mm} \setlength\lineskiplimit{-\maxdimen}}
    \usepackage{titlesec}
    \usepackage{titling}
    \usepackage{layouts}

    \usepackage{tikzpagenodes}
    \usepackage{lipsum}

    \usepackage{background}
    
    \definecolor{notepadrule}{RGB}{217,244,244}
    \usetikzlibrary{calc}
    \usepackage{tikz}
    \usepackage{setspace}
    \usepackage{parskip}
    \setlength{\parskip}{0pt}

    % Ajuste del espaciado antes y después de los encabezados
    \usepackage{leading}
    
    % Configuración del interlineado para que coincida con el papel milimetrado
    \setstretch{1.25} % Ajusta este valor para que coincida con la cuadrícula del papel
    
    % Ajuste del espaciado antes y después de los encabezados
    \titlespacing*{\section}
    {0pt}{0.5\baselineskip}{0.5\baselineskip}
    \titlespacing*{\subsection}
    {0pt}{0\baselineskip}{0\baselineskip}
    \titlespacing*{\subsubsection}
    {0pt}{0.5\baselineskip}{0.5\baselineskip}

    \backgroundsetup{%
     position=current page.center,
     angle=0,
     scale=1,
     contents={%
      \begin{tikzpicture}%
        [
          normal lines/.style={blue, very thin},
          red lines/.style={red, thick},
          every node/.append style={black, align=center, opacity=1}
        ]
        \foreach \y in {0mm,3mm,9.5mm,16mm,22.5mm,29mm,35.5mm,42mm,48.5mm,55mm,61.5mm,68mm,74.5mm,81mm,87.5mm,94mm,100.5mm,107mm,113.5mm,120mm,126.5mm,148mm}
          \draw[normal lines] (0,\y) -- (8.5in,\y);
        \draw[red lines](0,133mm) -- (8.5in,133mm);
      \end{tikzpicture}%
    }}
---
Agrupan Datos del mismo tipo. Para elementos de otros tipos: **[[Listas Generalizadas en R]]**.

Si al crear un vector los elemento no son heterogéneos, R los convierte al tipo que pueda englobar todo, en este orden de prelación:
````LOGIC->integer->numeric->complex->character````
		
### c()
Define un vector a partir de los datos entre paréntesis.
Puede usarse para concatenar vectores existentes.
'c' de "concatenar".

### rep(a,n) 
Crea un vector de elementos repetidos "a" n veces.
			
### scan()
Vacío, crea el vector a partir de datos introducidos por consola.

Permite crear un vector a partir de una url.

Permite crear un vector a partir de un fichero.
			
Parámetros importantes:

* Dec para el carácter decimal (dec = ",")
* Sep para el separador. (sep=",")
* What para la conversión (what = "character")
				
### class()
Devuelve el tipo de datos que contiene el vector.
	
\pagebreak

# References
## References2
processing file: R-Data-Structures.Rmd
output file: R-Data-Structures.knit.md
Error: LaTeX failed to compile R-Data-Structures.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See R-Data-Structures.log for more info.
Execution halted
